### ISSUE TITLE
"failed to fetch installation id" and issue with token expiration time

### ISSUE THREAD

**Issue by JyrkiHei** [Link-/gh-token#17]
Hi and thanks for this great script!
I have been playing around with it during last days and it has worked mostly fine and usually the errors are something that I did :D

I reinstalled my WSL-machine and something changed, because I started getting an error constantly saying:
"! failed to fetch installation id"

After debugging I got these errors from the installation ID fetch logic:
**"message": "'Expiration time' claim ('exp') is too far in the future"**

I knew that GitHub maximum for token expiration was 10mins and somehow my systems time was off synch half a second or something :) I tried to fix it with NTP etc, but nothing worked.I found some communication from different forums that when the endpoint (GitHub) is really strict about this, you should basically not call the maximum expiration time never. Usually the workaround was to decrease the expiration payload by one second so minor off-synch was allowed.

So all it took was to change the JWT-token generation line to:
-e $(( $(date +%s) + $(( _duration * 60 -1 )) )) \

https://github.community/t/expiration-time-claim-exp-is-too-far-in-the-future-when-creating-an-access-token/13830/2#M1127

Don't know if this is something that should be in the code, but atleast it's documented here if someone else gets this problem!

**Comment by Link-** [comment]
Damn! That's a nice catch @JyrkiHei. Thank you for contributing this information 🙇‍♂️

**Comment by Link-** [comment]
Closing as there's no action to be taken on this.
